-- Categories seed (derived from product sheet)
insert into categories (name) values
('(1 1/4 X 1 1/4) Square Tube'),
('(1 X 1 1/2 ) Rectangle Tube'),
('(1 X 1 1/2) L Channel'),
('(1 x 1)  L Channel'),
('(2X1) Rectangle Tube'),
('(3X1) Rectangle Tube'),
('(4X1) Rectangle Tube'),
('2" Gazing Plate'),
('8 cm Heavy Tube'),
('Adjustable Rack Pin'),
('Box Tube'),
('Box Tube Connector'),
('Bumper'),
('Cornis'),
('Crystal 3MM'),
('Cup & Sauces (Basket)'),
('Cutlery (Basket)'),
('Door'),
('Door Frame Channel'),
('Drawer Tube'),
('E Channel'),
('Easy Fold'),
('F Channel (Big)'),
('F Channel (Small)'),
('G Profile Handle'),
('G Profile Handle Cap'),
('Glass Channel'),
('Glass Door'),
('H Channel'),
('Hanger Fitting'),
('Hinges'),
('Hydraulic Lift'),
('J Channel'),
('Kerala Box Tube Double'),
('Kerala Box Tube Single'),
('Louver Panel'),
('Luka Handle'),
('Luka Handle Cap'),
('Mill Finish'),
('Mirror Bracket'),
('Mirror Handle'),
('Oil pullout (Adjustable)'),
('Oil pullout (Fixed)'),
('Plain (Basket)'),
('Plate (Basket)'),
('Push to Open'),
('Rivet 3mm'),
('Rivet 4mm'),
('SS Ventilator'),
('Screw'),
('Silicon'),
('Square Double Lip'),
('Square Single Lip'),
('Tandem Drawer'),
('Telescope (SS)'),
('Telescope (Zinc)'),
('Tower Bolt'),
('U Channel  (Big)'),
('U Channel  (Small)'),
('U Track Big'),
('Wooden Hinges')
on conflict (name) do nothing;
